name: cron

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: "1.18.5"

      - name: Run command
        shell: bash
        env:
          SWITCHBOT_OPEN_TOKEN: ${{ secrets.SWITCHBOT_OPEN_TOKEN }}
          SWITCHBOT_SECRET_KEY: ${{ secrets.SWITCHBOT_SECRET_KEY }}
          SWITCHBOT_DEVICE_ID: ${{ secrets.SWITCHBOT_DEVICE_ID }}
          OPENWEATHER_APP_ID: ${{ secrets.OPENWEATHER_APP_ID }}
          OPENWEATHER_CITY: ${{ secrets.OPENWEATHER_CITY }}
        run: |
          go run cmd/weather-forecast-lamp/main.go
